### ISSUE TITLE
Won't work in Laravel > 4.0.*

### ISSUE THREAD

**Issue by afraca** [jijoel/validation-rule-generator#1]
Hey, I'm interested to use this package, to automate some stuff away. But with the current requirements for composer this won't work in newer Laravel versions. I'm didn't really look into how much trouble it would be to port, as I'm quite new  to Laravel I'm unsure how much has changed since 4.0.

**Comment by jijoel** [comment]
Heh... such a long, long time ago. :-) If you're still interested, I just made some modifications that should make it work with modern versions of Laravel.
